nginx:
    build: ./MyNginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    depends_on:
        - node1
        - node2
        - node3
    ports:
        - "80:80"
node1:
    build: ./NodeApp
    ports:
        - "3000"
node2:
    build: ./NodeApp
    ports:
        - "8080"
node3:
    build: ./NodeApp
    ports:
        - "3000"

