version: "2"

networks: 
  ci-net: 
   driver: bridge
services: 
  jenkins: 
    build: 
      context: ./jenkins2.0
      dockerfile: jenkins_tls.dockerfile
      args:
        DOCKER_HOST: $DOCKER_HOST
    volumes:
      - /home/docker:/var/jenkins_home
    depends_on: 
      - nexus
      - sonar
      - selhub
    links: 
      - "nexus:nexus"
      - "sonar:sonar"
      - "selhub:selhub"
    networks: 
      - ci-net
    ports: 
      - "18080:8080"
      - "50000:50000"
  nexus: 
    build: ./nexus3
    networks: 
      - ci-net
    ports: 
      - "18081:8081"
      - "14243:4243"
  nodech: 
    depends_on: 
      - selhub
    environment: 
      - HUB_PORT_4444_TCP_ADDR=selhub
    image: selenium/node-chrome-debug
    networks: 
      - ci-net
    ports: 
      - "15900:5900"
  nodeff: 
    depends_on: 
      - selhub
    environment: 
      - HUB_PORT_4444_TCP_ADDR=selhub
    image: selenium/node-firefox-debug
    networks: 
      - ci-net
    ports: 
      - "15901:5900"
  selhub: 
    image: selenium/hub
    networks: 
      - ci-net
    ports: 
      - "14444:4444"
  sonar: 
    build: ./sonar
    depends_on: 
      - sonardb
    environment: 
      - "SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar"
    networks: 
      - ci-net
    ports: 
      - "19000:9000"
      - "15432:5432"
  sonardb: 
    environment: 
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    image: postgres
    networks: 
      - ci-net
